name: Continous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    name: ci - ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Build
        run: go build
      - name: Test
        run: go test
